name: balmoranews
description: "a flex and news app"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  adaptive_formula:
    git:
      url: https://github.com/bgoncharuck/adaptive_formula.git
      ref: dbb27befe052cc29872dfb378db7dc2c41c84e43
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  get_it: ^9.0.5
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

  # since we are required to use flutter_bloc which depends on Provider
  # we can use connectivity_wrapper which is also depends on Provider
  provider: ^6.1.5+1
  connectivity_wrapper: ^1.2.8
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1


dev_dependencies:
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  flutter_dotenv: ^6.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: false
  assets:
  - assets/images/
  # must not be included in a release build
  - .env

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

# dart run flutter_native_splash:create
flutter_native_splash:
  background_image: splash.jpg